exclude: >
  (?x)^(
    backend/static|
    backend/fixtures|
    backend/.+/migrations
  )

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        files: ^(app|tests)/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python3.12
        files: ^(app|tests)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]  # 자동 수정
        files: ^(app|tests)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        language_version: python3.12
        files: ^(app|tests)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: double-quote-string-fixer
    - id: detect-private-key
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
      files: ^(app|tests)/