name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.13"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python (via setup-python)
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Sync dependencies
      run: |
        uv sync --dev --locked || uv pip install -r requirements.txt

    # 코드 스타일 검사
    - name: Check formatting with black
      run: |
        uv pip install black
        uv run black --check app tests

    - name: Check import order with isort
      run: |
        uv pip install isort
        uv run isort --check-only app tests

    - name: Lint with ruff
      run: |
        uv pip install ruff
        uv run ruff check app tests

    # 타입 검사
    - name: Type check with mypy
      run: |
        uv pip install mypy
        uv run mypy app

    # 테스트 실행
    # - name: Run pytest
    #   run: |
    #     uv pip install pytest
    #     uv run pytest tests
